apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: chatbot
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: chatbot-ui
spec:
  source:
    git:
      url: https://github.com/mckaywrigley/chatbot-ui.git
      ref:
        branch: main
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
      cpu: 500m
  params:
  - name: dockerfile
    value: Dockerfile
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: skip
